# docker compose docs: https://docs.docker.com/compose/compose-file/

# docker compose version
version: '3.7'

services:

  database:
    image: postgres:12
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  tests:
    build: .
    command: pytest
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}"
    volumes:
      - .:/project

  migrations:
    build: .
    command: alembic -c setup.cfg upgrade head
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}"
    volumes:
      - .:/project

  server:
    build: .
    command: flask run --port ${SERVER_PORT} --host 0.0.0.0
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/project
