# docker compose docs: https://docs.docker.com/compose/compose-file/

# docker compose version
version: '3.7'

services:

  web:
    container_name: web
    build: .
    command: bash -c "pipenv sync && pipenv run flask run --port ${SERVER_PORT} --host 0.0.0.0"
    working_dir: /project
    environment:
      PIPENV_VENV_IN_PROJECT: "${PIPENV_VENV_IN_PROJECT}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      # mount root directory
      - .:/project
