# docker compose docs: https://docs.docker.com/compose/compose-file/

# docker compose version
version: '3.7'

services:

  database:
    container_name: database
    image: postgres:12
    stop_grace_period: 30s
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  lint:
    container_name: lint
    build: .
    volumes:
      - .:/project

  tests:
    container_name: tests
    build: .
    command: pytest
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}"
    volumes:
      - .:/project
    links:
      - database

  migrations:
    container_name: migrations
    build: .
    command: alembic -c setup.cfg upgrade head
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}"
    volumes:
      - .:/project
    links:
      - database

  server:
    container_name: server
    build: .
    command: gunicorn --reload "server.app:create_app()" --bind 0.0.0.0:${SERVER_PORT}
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/project
    links:
      - database
