"""
schema.py contains all of the input and output schemas for our server

The schemas are all defined with marshmallow, which you can read about here
=> https://marshmallow.readthedocs.io/

🚨 Changing the keys on the schemas will change the inputs and outputs for our server.
🚨 So before you change the keys, please check that all of our clients are updated!

The schemas are tested by writing tests for the controllers. We could instead choose to
test the schemas directly, if they controller tests (and their database calls) become
too heavy.

TODO - pipe all of these into autogenerated OpenAPI v3 definitions.
"""

from typing import List

from marshmallow import EXCLUDE, Schema, ValidationError, fields, validate
from marshmallow.validate import Range


# disable "too few public methods" warning, the schemas inherit public methods from their base class
# pylint: disable=R0903


class UserSchema(Schema):
    """
    UserSchema represents the schema that clients input into our server, or
    recieve as output from our server.

    So for example, it is the schema that you should respect when `POST`ing the server.

    When used as input, it looks like so:
    {
        "email": "lynncyrin@gmail.com",
        ...
    }

    When used as output, it looks like so:
    {
        "user_id": 1234, # <== newly added
        "email": "lynncyrin@gmail.com",
        ...
    }
    """

    user_id = fields.Integer(dump_only=True)
    email = fields.Email(required=True)
    name = fields.Str(required=False, validate=validate.Length(max=10000))

    class Meta:
        unknown = EXCLUDE


class UserPathParamSchema(Schema):
    """
    UserPathParamSchema represents the path parameter schema to use when making GET requests
    for our users endpoints.

    For example, given the request...
    GET /users/5000
               ^
               the schema defines the data input here
    """

    user_id = fields.Integer(
        required=True, validate=[Range(min=0, error="must not be negative")]
    )

    class Meta:
        unknown = EXCLUDE


class UserQueryParamSchema(Schema):
    """
    UserQueryParamSchema represents the query string schema to use when making GET requests
    for our users endpoints.

    For example, given the request...
    GET /users?page=20&limit=10
              ^
              the schema defines the data from this point, and on.
    """

    # WRT both `default` and `missing` being present here, see
    #  => https://github.com/marshmallow-code/marshmallow/issues/775
    page = fields.Integer(
        default=1, missing=1, validate=[Range(min=0, error="must not be negative")]
    )
    limit = fields.Integer(
        default=50,
        missing=50,
        # 1000 is my napkin math estimate for the a number that will prevent the server
        # overloading the database with massive GET requests
        validate=[
            Range(max=1000, error="limit must be less than 1000"),
            Range(min=0, error="must not be negative"),
        ],
    )
    sort_by = fields.String(
        default="", missing=""
    )  # validate that its actually a column name
    order = fields.String(
        default="desc", missing="desc"
    )  # validate that its "desc" "asc"

    # # {
    # #   nextUrl: "GET /users?page=2020-01-01-TZUS&limit=2020-02-01-TZUS"
    # # }
    # nextUrl = fields.String()

    class Meta:
        unknown = EXCLUDE
