"""new user data

Revision ID: 79d8f23d7fe1
Revises: b39c2bfdd80a
Create Date: 2020-04-29 01:06:58.208341

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '79d8f23d7fe1'
down_revision = 'b39c2bfdd80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('familyName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('givenName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('smsUser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'smsUser')
    op.drop_column('users', 'role')
    op.drop_column('users', 'givenName')
    op.drop_column('users', 'familyName')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
