
name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: checkout code
        uses: actions/checkout@v2

      - name: install prereqs
        run: pip install pipenv && pipenv sync --dev

      - name: run tests
        run: pipenv run pytest
