name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1

    - name: Run a one-line script
      run: echo Hello, world!

    - name: install dependencies
      run: pip install pipenv && pipenv sync --dev
